services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    environment:
      - DOMAIN_NAME=${CADDY_DOMAIN}
    depends_on:
      - app
    networks:
      - app-network

  app:
    build: .
    ports:
      - "0.0.0.0:${APP_PORT:-8490}:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - EMAIL_NOTIFICATIONS_ENABLED=${EMAIL_NOTIFICATIONS_ENABLED:-yes}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "59103:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: America/Bogota
    command: --default-time-zone=-05:00
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  caddy-data:
  caddy-config:
