version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - app
    networks:
      - app-network

  app:
    build: .
    ports:
      - "0.0.0.0:8490:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    secrets:
      - db_host
      - db_name
      - db_username
      - db_password

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/mysql
    networks:
      - app-network
    secrets:
      - db_root_password
      - db_name

secrets:
  db_host:
    file: ./secrets/db_host.txt
  db_name:
    file: ./secrets/db_name.txt
  db_username:
    file: ./secrets/db_username.txt
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  caddy-data:
  caddy-config:
